project:
  type: website

website:
  title: "QG Doc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: geographic.qmd
        text: Geographic Files
      - href: cycleWalk.qmd
      - href: atlasIO.qmd
        text: Atlas Files
      - about.qmd
  sidebar: 
    style: "docked"
    search: true
    depth: 2
    contents:
      - text: Geographic Files
        href: geographic.qmd  
      - text: "Cycle Walk"
        href: cycleWalk.qmd
      - text: "Atlas Files"
        href: atlasIO.qmd      

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



