---
title: "Quantifying Gerrymandering Project Documentation"
bibliography: ref.bib
csl: apa
---

This site gives introductions to some of the tools developed by the *Duke Quantifying Gerrymandering* group. The group, headed by [Jonathan C. Mattingly](https://sites.math.duke.edu/~jonm/) and [Gregory J. Herschlag](https://scholars.duke.edu/person/gjh), works to understand how to assess the degree to which political districts capture the will of the people in the elections in which they are used.The group has benefited from collaboration countless colleagues and students. For more information, please see the groups [blog](https://sites.duke.edu/quantifyinggerrymandering/).

A few tools of possible particular interest are:

- **[Cycle Walk](cycleWalk.qmd):** A Julia implementation of a promising algorithm to sample an ensemble of redistricting maps from a specified measure on the space of all redistrictings.
- **[Metropolized Forest RECOM](forest_recom.qmd):** An algorithm that modifies the original RECOM algorithm so that it can better sample from a specified probability distribution. and so that it can better preserve geographical structure like counties. [See @autry2023metropolized]
- **[Metropolized Multi-scale Forest RECOM](forest_recom.qmd):** An algorithm that modifies further modifies  Metropolized Forest RECOM so that it runs on a multiscale graph. One advantage is that it can better preserve geographical structure like counties. [See @autry2021metropolized]
- **[Atlas File Format](atlasIO.qmd):** The format used by the Quantifying Gerrymandering Project's software to efficiently store and document a collection of maps. The AtlasIO packages in Julia and Python can be used to read and process the files. 



